config:
  validation: true
  warningsAsErrors: true

complexity:
  LargeClass:
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
  CyclomaticComplexMethod:
    ignoreSimpleWhenEntries: true
    ignoreAnnotated:
      - 'Composable'
  LongMethod:
    ignoreAnnotated:
      - 'Composable'
  LongParameterList:
    allowedFunctionParameters: 10
    allowedConstructorParameters: 10
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    allowedFunctionsPerClass: 15
    allowedFunctionsPerInterface: 16
    ignoreAnnotatedFunctions:
      - 'Composable'
      - 'Preview'

naming:
  FunctionNaming:
    ignoreAnnotated:
      - 'Composable'
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'

style:
  ForbiddenComment:
    active: false
  MagicNumber:
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreEnums: true
  MaxLineLength:
    maxLineLength: 120
    excludeCommentStatements: true
    excludePackageStatements: true
    excludeImportStatements: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
  UnusedImport:
    active: true
  UnusedPrivateFunction:
    ignoreAnnotated:
      - 'Preview'
  UnusedPrivateProperty:
    ignoreAnnotated:
      - 'Preview'
  WildcardImport:
    active: true

Compose:
  active: true
  ParameterNaming:
    active: false
